mysql:
  user: 'root'
  password: 'asdfasdf'
  host: localhost
  database: mememana
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
manaRotTime: 30d
manaGainTimeout: 22h
maximumDailyMana: 10
pearlRefillAmount: 
  EXILE: 168 # 1344 pearl hp units per week divided by 8 mana per week = 168 pearl hp units per mana
  PRISON: 21 # 1344 pearl hp units per week divided by 64 mana per week = 21 pearl hp units per mana
pearlUpgradeAmount: 64
